import jusungSolution from './jusung.js';
import jiwooSolution from './jiwoo.js';
import dowooSolution from './dowoo.js';
import soowonSolution from './soowon.js';

describe('680. Valid Palindrome', () => {
  const arr = [
    {
      input: 'aba',
      output: true,
    },
    {
      input: 'aa',
      output: true,
    },
    {
      input: 'aaa',
      output: true,
    },
    {
      input: 'abca',
      output: true,
    },
    {
      input: 'abc',
      output: false,
    },
    {
      input: 'abcc',
      output: false,
    },
    {
      input: 'acbdbdca',
      output: true,
    },
    {
      input:
        'dzpixsvdjecobotafvqrweqfviyfnzkowkyfcmmkeprsqnljywgdcmozipvaoouumzfgaxjdhwuotetbjjxyvllehlplajlvrjgfcvdzhhbydhokkxqbnevakjqpytjvilnhypzkjuieaydavghdtotjegnwfuqyvumflrhfnwjumcomvzvvddscwjkkjtozohcfttzvdeeokzyqcjnwcfglpmfaijldwggvydamqjclkzlknabnqvpadlcxwhkfnodysztswdbtvebcdpmecupvcfkjytiduzdetuhftzwtnpdtckggkoppwgnoezlewxunpyparrjnficgtclffkiukbgtddawtawsjgqjnebjnfgvamlqqgsdcialostdqkyrjkrhxqgcljrzlxutoeybkiyverihjftjnpjbywqjesifhoplxjxdcdvdoukiqsdqwqfxdeyamliicibyfsrsgfadedpgilcvxrqvzbtvpfzcddjdejkcxtaosiqhijpdvcmldwzoemcspkmpotxbqefnljfunbjkhifqmbzftnzmcoodzyvlimbfuxauvllpkvrkgpfynqxcopujwmnmqgvihhijibxfoafyaqvixllbfyqhkqzbrmoltwugiaeuyhjzengivorjucjkmvzscxnuwfvbpaqfepfswwyfseccwlbxarbweghmrahljkziwpjxhsiwqgkcxwagwyssxckskdcpmqorqykfcpprobysmakisphwviplhyhoccedepxihkoakthzxifhquaywjunovnbupylenkmloractfjhbvrbgqcjrlypblysnbhmmcnonythrzqnhxrwgucbrdtbiqrpzdufsnsntjfhnuajzwugwheecluvortahttabeqkesmmgtvrrhmcbjemgvtfbfbtdmzeugidfftnvhgbvmdjqzxngtaloelidkgtejfwgqgjjdmvkcfjudybxclraoifqkxyndwzpwcyfnjofvmfavqhhkhgrozpxecfgafwpjaxvrzgsshfrurzvxuyxembsidbfaxdtcbzenlkqwdiyvfrsesdxbampomvyzfwhqmnyrohpzvkhmtigbqbgjcwbsfahwrasyjhkasbqblkkbastkztnwgsizrmgpfcsfnwqsfzkqtjksrozdaigyechulbmgqxtkdxsxkmcqfshdoaqnlaujshbczdfnpiohadccbascecxakgvcjpfjevvtdwbzwpjfimizudynnvfyuiktjjkhtiemhcooidhphaxswjtymeekyhbgfqfiqucslyyrkilqqftyhublazhonktlcxxhhdjcjewokyjvqtrhibfjkoepwaegbjmjakqusxjmrpceigpzcpgjsvluidmmiqcqshroejnzutlyqbmzhivscscbhvgapkleiyezwhfglvckbzjikdtyyuchlvdwmjapdjddfdaevxnseuikjrwknkleeidmgiazrhwlhyufwvqochvzwlpphhvyqhnbfcpgguqdozwijirlyehiejfpzwyxzokcslvexryarsghwyiiefkyhmblvrzeohglrwdlxuvceewsplpokxaempvsagqoowgaylotbkkgxmnbqfuqdiflapspidzpjnwmkentzysoldgcckxhwmayivsdojkpjuhxarhueimplixljmuamzcjlgpgstwzmagzeeeffsmnffalafafxdaunpmgpvtihygbplkvtjzcikurdhefjlaquxidmbxxyamampoolkwxvsbiibkehxnzktdfjyumjfbwxmjccfkhoxtljmqlnkxscqpvtzvubyvndfmrzfcydjkcerzwrszoxjdoykjapbpocripynleomortlfwoimoiaqzonrxzyxzitdyykenwlyvzulkzamylknzikxgmgwyhmjrafbnksijetqjijybctfkhivjmotxplydxtdodmmjgacdwedaibuzzbjjlnineqskouoneipimxxhmnzxshjfwgcwgfslpjfekoiwvwgjewdbtimyxzvkancdvdykgfxpeptjonnlhdaerkyznctrpshuetjqhigncnebokuewgtufndvdkkvvptnmxpfkazmulpmspaagfngdvxggxmaagskwnmursusnaaaklajvqfkobdbwyvnmslahyijmrmiqwgawbwnocbgedkqvsmnwffgqjoskymxkbkbzrskjuteqkbpqyhmzeyrwzwiakphmmpacqnrkxgmsnfqwhihustnyflrlqfygwngyrosbnkkesmkezbmnzxgbhereemjmwwflieuuxxuwiftxdvgieyyqhzducjhphrlaaqarxmjxmdqhcplytkaarpwbvsmfxotwjztlgenivifikpqnbgcxgmbnbbqgysyanezknimleepwgsmjoqbsvkedyxiifkvrekqvkbrtgaywqxfepaqmbgpbdyfgseuzwycmppmgymopwozufrybewvkbyliicrqknvotcloxkihyparuftlgfqlyrccsdyxrlallnwqoocdwrqrwacyogsfocqfwrmfnwfwypcktocjhtucvdnfunhdppjubmyeqkeljifqgvihzdvxmjvgtrtucyiznindedfjfgtqmzoxvbexyeceltuxpqtjrjlgzgxcggzvpiagjgclwfqcyjgwlxtpwfwzbuxleuooplkuxozfuthkuwqyjixkxejscwddvqwqrekcnqeatduaoonjaanhqsrzcfrkulvjowkavjfzqydsqiitqaqjandtznsfofhrtokmamqjsprrlxuktccirufccgqvaegwtlbvceitfhwwcykivxydhdrfuutnhdabkxwlpjuqtoppxelpknaunugddmtihitvvrqchxyyakeyyloxeuroygfpplcecirtvydnscorwsgscsxfcjcwgjrbzbttyklszhtdcjpkkifkztgwjmhetzjjzdpbhtdpiiarvgxdwagujyjepmnaenkqvhjifvtydzncuayoofdnzlxkscgjlyevdmbikrkkhvbmiabkotnqszezghojgkinepkgshfkfwfdsatdgdmbffcvknyvtfavjnyjmybjtlsrypmljkqqcuuenpqaslbdexfyvzslvjwdogmveppdotyedzjjmirqdpfimhwslntrmjvfjqushrpnbtzwfufcokvdtubppxzrmbuwdgyuxielaaetaoptrqjihdhzhwohfmlmoofgxjoxlzrrnpmxshmlorvbpfytzkbnirjpszbofeqckjxtxpkrtgprsmjyyuhdakvzlkzvlvnkxloldpwnrmgmrlgsnapsfqbbspsfxasqvktesjzbtobfrcydxunahscsehothdguhxcwwhxjzhfhyczzgipqqvivgnrymvggwyjbplyghitidfqhpamnmmukwjskccvsvdxrbkqegziagsrfmcsiombjlpidbiyahqlyivqlupuozvqqalokxslnisllfbhhynozvpondxnkopvgwtewykxlxqgiemqgugisaerqsjfzlyrdzezzloyzxwhnrobplkqmlkioyyyarkgupopjrlwfypvkjnbuzkkdioeakabhlefrjgpapxwxfmtkwtivfeswvhggojdafkhorkehsivpeezyhgfmblikmnkluzzrmpamidodgjnacghqxyaanvbgvhjxdvozbgyegmbvyuwydsaushuyfahiwhwcmwamoreoldyoriaifafqlmycuodhrfmysalzezcovxvjftoxtphwihbslfpieujnindpbrikbzelxgsqnyghtzklsdhiwilodlynekgebebocqkqbelnvkcltwyeuxgmbuadrlnunwhgfypfpcughajteiqrwsyhpbfeguflxfrxhhdjbuxhelcmsvrztlluthmhmzlwcwbxiaqajuyoxymjabqnfepofffwqrjfqamzhouzanyhslumwqedbveslxqbzcjjrlkyfhaloaiegvqbypzazwytkablpkfcoyruyivbqsgbeaubygvftllwbzijwmeyxpvlqpichbovsndgtnjwkorlgbypsstwabstxvfewmrjlzfylmopmohueojobwmipjbpyapuhvqqnczjnbbvragvslaljfswviqyfpzsunjnsuaywubparidngjuibinsdbxjdmgfuxtuipokbfevrlambsxhyqmnkhjvlboixjvrbasprbxdwdwwzjizgevtyiehcszbuvsxgjrbmqgnylwmfvfpxxbnowbfmprqyupzmjnsbsgjvxfibjyuniiuicxfhqyecahxmhooqmosqwwliaglldtcrizdjtazniwpflilywhwmrjcyovttjlxvfodcmzgequccxfjgzrjsreohmwqdqqibdzggwcexxmzayohloewswdugzuibjlfrixlmmzeqgoawqbveaetjnilkvumrmvsuknbmmyypqzxxyojzwbbnwtfwoofsqwlrprbtpxjqgceekmixzewjnokxehqqshcsbmvauchcvhqnfrinklmylddbszvzuahxnvhlswqvzcnwnazuuipxzzdmoylcczsuhxihrjolvhkcdagffsqqxvzuvakqqscbakkhumzxwlhfdaqqlkbohfpvrozbmmyebpqjcyeqqhvirsjemfotyxfwgjzsvpyktdcbennxgbskdbqjoqakwbxyeyszgeyhwclymadtqxwepkfyxglmtzdscffnzzkceutahpiavpoorrphrvodzvqkxldhwfrkevkthofwocbcberfrfoxkyyidwpvhkfgnhuaetitjtmucdtlflgqjdafokoiootmluimwbatkshskqxfduhzikhhgqctadqpsfryuzozfnfqpjvmmrfxlfsuatovazmnthrrlxhagycjakhviigfqwwqfgiivhkajcygahxlrrhtnmzavotausflxfrmmvjpqfnfzozuyrfspqdatcqghhkizhudfxqkshsktabwmiulmtooiokofadjqglfltdcumtjtiteauhngfkhvpwdiyykxofrfrebcbcowfohtkvekrfwhdlxkqvzdovrhprroopvaiphatueckzznffcsdztmlgxyfkpewxqtdamylcwhyegzsyeyxbwkaqojqbdksbgxnnebcdtkypvszjgwfxytofmejsrivhqqeycjqpbeymmbzorvpfhobklqqadfhlwxzmuhkkabcsqqkavuzvxqqsffgadckhvlojrhixhuszcclyomdzzxpiuuzanwnczvqwslhvnxhauzvzsbddlymlknirfnqhvchcuavmbschsqqhexkonjwezximkeecgqjxptbrprlwqsfoowftwnbbwzjoyxxzqpyymmbnkusvmrmuvklinjteaevbqwaogqezmmlxirfljbiuzgudwsweolhoyazmxxecwggzdbiqqdqwmhoersjrzgjfxccuqegzmcdofvxljttvoycjrmwhwylilfpwinzatjdzirctdllgailwwqsomqoohmxhaceyqhfxciuiinuyjbifxvjgsbsnjmzpuyqrpmfbwonbxxpfvfmwlyngqmbrjgxsvubzscheiytvegzijzwwdwdxbrpsabrvjxioblvjhknmqyhxsbmalrvefbkopiutxufgmdjxbdsnibiujgndirapbuwyausnjnuszpfyqivwsfjlalsvgarvbbnjzcnqqvhupaypbjpimwbojoeuhompomlyfzljrmwefvxtsbawtsspybglrokwjntgdnsvobhcipqlvpxyemwjizbwlltfvgybuaebgsqbviyuryocfkplbaktywzazpybqvgeiaolahfyklrjjczbqxlsevbdeqwmulshynazuohzmaqfjrqwfffopefnqbajmyxoyujaqaixbwcwlzmhmhtulltzrvsmclehxubjdhhxrfxlfugefbphyswrqietjahgucpfpyfghwnunlrdaubmgxueywtlckvnlebqkqcobebegkenyldoliwihdslkzthgynqsgxlezbkirbpdninjueipflsbhiwhptxotfjvxvoczezlasymfrhdoucymlqfafiairoydloeromawmcwhwihafyuhsuasdywuyvbmgeygbzovdxjhvgbvnaayxqhgcanjgdodimapmrzzulknmkilbmfghyzeepvishekrohkfadjogghvwsefvitwktmfxwxpapgjrfelhbakaeoidkkzubnjkvpyfwlrjpopugkrayyyoiklmqklpbornhwxzyolzzezdrylzfjsqreasigugqmeigqxlxkywetwgvpoknxdnopvzonyhhbfllsinlsxkolaqqvzoupulqviylqhayibdipljbmoiscmfrsgaizgeqkbrxdvsvccksjwkummnmaphqfditihgylpbjywggvmyrngvivqqpigzzcyhfhzjxhwwcxhugdhtohescshanuxdycrfbotbzjsetkvqsaxfspsbbqfspansglrmgmrnwpdlolxknvlvzklzvkadhuyyjmsrpgtrkpxtxjkcqefobzspjrinbkztyfpbvrolmhsxmpnrrzlxojxgfoomlmfhowhzhdhijqrtpoateaaleixuygdwubmrzxppbutdvkocfufwztbnprhsuqjfvjmrtnlswhmifpdqrimjjzdeytodppevmgodwjvlszvyfxedblsaqpneuucqqkjlmpyrsltjbymjynjvaftvynkvcffbmdgdtasdfwfkfhsgkpenikgjohgzezsqntokbaimbvhkkrkibmdveyljgcskxlzndfooyaucnzdytvfijhvqkneanmpejyjugawdxgvraiipdthbpdzjjztehmjwgtzkfikkpjcdthzslkyttbzbrjgwcjcfxscsgswrocsndyvtriceclppfgyoruexolyyekayyxhcqrvvtihitmddgunuankplexppotqujplwxkbadhntuufrdhdyxvikycwwhftiecvbltwgeavqgccfuricctkuxlrrpsjqmamkotrhfofsnztdnajqaqtiiqsdyqzfjvakwojvlukrfczrsqhnaajnooaudtaeqnckerqwqvddwcsjexkxijyqwukhtufzoxuklpoouelxubzwfwptxlwgjycqfwlcgjgaipvzggcxgzgljrjtqpxutleceyxebvxozmqtgfjfdedninziycutrtgvjmxvdzhivgqfijlekqeymbujppdhnufndvcuthjcotkcpywfwnfmrwfqcofsgoycawrqrwdcooqwnllalrxydsccrylqfgltfurapyhikxolctovnkqrciilybkvwebyrfuzowpomygmppmcywzuesgfydbpgbmqapefxqwyagtrbkvqkervkfiixydekvsbqojmsgwpeelminkzenaysygqbbnbmgxcgbnqpkifivinegltzjwtoxfmsvbwpraaktylpchqdmxjmxraqaalrhphjcudzhqyyeigvdxtfiwuxxuueilfwwmjmeerehbgxznmbzekmsekknbsorygnwgyfqlrlfyntsuhihwqfnsmgxkrnqcapmmhpkaiwzwryezmhyqpbkqetujksrzbkbkxmyksojqgffwnmsvqkdegbconwbwagwqimrmjiyhalsmnvywbdbokfqvjalkaaansusrumnwksgaamxggxvdgnfgaapsmplumzakfpxmntpvvkkdvdnfutgweukobencngihqjteuhsprtcnzykreadhlnnojtpepxfgkydvdcnakvzxymitbdwejgwvwiokefjplsfgwcgwfjhsxznmhxxmipienouoksqeninljjbzzubiadewdcagjmmdodtxdylpxtomjvihkftcbyjijqtejisknbfarjmhywgmgxkiznklymazkluzvylwnekyydtizxyzxrnozqaiomiowfltromoelnypircopbpajkyodjxozsrwzreckjdycfzrmfdnvybuvztvpqcsxknlqmjltxohkfccjmxwbfjmuyjfdtkznxhekbiibsvxwkloopmamayxxbmdixuqaljfehdrukiczjtvklpbgyhitvpgmpnuadxfafalaffnmsffeeezgamzwtsgpgljczmaumjlxilpmieuhraxhujpkjodsviyamwhxkccgdlosyztnekmwnjpzdipspalfidqufqbnmxgkkbtolyagwooqgasvpmeaxkoplpsweecvuxldwrlghoezrvlbmhykfeiiywhgsrayrxevlsckozxywzpfjeiheylrijiwzodquggpcfbnhqyvhhpplwzvhcoqvwfuyhlwhrzaigmdieelknkwrjkiuesnxveadfddjdpajmwdvlhcuyytdkijzbkcvlgfhwzeyielkpagvhbcscsvihzmbqyltuznjeorhsqcqimmdiulvsjgpczpgiecprmjxsuqkajmjbgeawpeokjfbihrtqvjykowejcjdhhxxcltknohzalbuhytfqqlikryylscuqifqfgbhykeemytjwsxahphdioochmeithkjjtkiuyfvnnyduzimifjpwzbwdtvvejfpjcvgkaxcecsabccdahoipnfdzcbhsjualnqaodhsfqcmkxsxdktxqgmbluhceygiadzorskjtqkzfsqwnfscfpgmrzisgwntzktsabkklbqbsakhjysarwhafsbwcjgbqbgitmhkvzphorynmqhwfzyvmopmabxdsesrfvyidwqklnezbctdxafbdisbmexyuxvzrurfhssgzrvxajpwfagfcexpzorghkhhqvafmvfojnfycwpzwdnyxkqfioarlcxbydujfckvmdjjgqgwfjetgkdileolatgnxzqjdmvbghvntffdiguezmdtbfbftvgmejbcmhrrvtgmmsekqebatthatrovulceehwguwzjaunhfjtnsnsfudzprqibtdrbcugwrxhnqzrhtynoncmmhbnsylbpylrjcqgbrvbhjftcarolmknelypubnvonujwyauqhfixzhtkaokhixpedeccohyhlpivwhpsikamsyborppcfkyqroqmpcdkskcxssywgawxckgqwishxjpwizkjlharmhgewbraxblwccesfywwsfpefqapbvfwunxcszvmkjcujrovignezjhyueaiguwtlomrbzqkhqyfbllxivqayfaofxbijihhivgqmnmwjupocxqnyfpgkrvkpllvuaxufbmilvyzdoocmzntfzbmqfihkjbnufjlnfeqbxtopmkpscmeozwdlmcvdpjihqisoatxckjedjddczfpvtbzvqrxvcligpdedafgsrsfybiciilmayedxfqwqdsqikuodvdcdxjxlpohfisejqwybjpnjtfjhirevyikbyeotuxlzrjlcgqxhrkjrykqdtsolaicdsgqqlmavgfnjbenjqgjswatwaddtgbkuikfflctgcifnjrrapypnuxwelzeongwppokggkctdpntwztfhutedzudityjkfcvpucempdcbevtbdwstzsydonfkhwxcldapvqnbanklzklcjqmadyvggwdljiafmplgfcwnjcqyzkoeedvzttfchozotjkkjwcsddvvzvmocmujwnfhrlfmuvyqufwngejtotdhgvadyaeiujkzpyhnlivjtypqjkavenbqxkkohdybhhzdvcfgjrvljalplhellvyxjjbtetouwhdjxagfzmuuooavpizomcdgwyjlnqsrpekmmcfykwokznfyivfqewrqvfatobocejdvsxipzdq',
      output: true,
    },
  ];

  arr.forEach(({ input, output }) => {
    it(`주성 ${input} - ${output}`, () => {
      expect(jusungSolution(input)).toStrictEqual(output);
    });
  });

  arr.forEach(({ input, output }) => {
    it(`지우 ${input} - ${output}`, () => {
      expect(jiwooSolution(input)).toStrictEqual(output);
    });
  });

  arr.forEach(({ input, output }) => {
    it(`도우 ${input} - ${output}`, () => {
      expect(dowooSolution(input)).toStrictEqual(output);
    });
  });

  arr.forEach(({ input, output }) => {
    it(`수원 ${input} - ${output}`, () => {
      expect(soowonSolution(input)).toStrictEqual(output);
    });
  });
});
